version: "1"
services:
  - type: web
    name: yshops
    env: docker
    plan: free
    branch: master
    autoDeployTrigger: commit
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_KEY
        value: base64:uNhm4eZ9o7QuvZlCrvlPqD3EUaNqWP9gZjO5jS+Jk8c=
      - key: APP_URL
        value: https://yshops.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: containers-us-west-2.render.com   # remplace par l'host de ta base Render
      - key: DB_PORT
        value: '3306'
      - key: DB_DATABASE
        value: project_2                             # nom de ta base Render
      - key: DB_USERNAME
        value: abdourahmane                          # user de ta base Render
      - key: DB_PASSWORD
        value: dash                                   # mot de passe de ta base Render

