envVars:
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: 'false'
  - key: APP_KEY
    value: base64:uNhm4eZ9o7QuvZlCrvlPqD3EUaNqWP9gZjO5jS+Jk8c=
  - key: APP_URL
    value: https://yshops.onrender.com   # Remplace par l'URL Render
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    value: <Render-MySQL-host>
  - key: DB_PORT
    value: '3306'
  - key: DB_DATABASE
    value: <Render-MySQL-database>
  - key: DB_USERNAME
    value: <Render-MySQL-username>
  - key: DB_PASSWORD
    value: <Render-MySQL-password>

