# Exported from Render on 2025-11-23T15:53:21Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: yshops
      runtime: node
      repo: https://github.com/Ndiouroul/yshops
      plan: free
      region: oregon
      buildCommand: npm install
      startCommand: node vite.config.js
      autoDeployTrigger: commit
